### ISSUE TITLE
Питон для анализа генетических данных

### ISSUE THREAD

**Issue by alexaibio** [minskpython/talks#44]
примерный план (будет меняться)

- 3-4 слайда про днк/рнк/протеины и форматы данных для них
- мутации и формат данных для них
- зачем мы это делаем и что можем извлечь из этих данных: популяционная генетика,  пренатальная диагностика, диагностика генетических заболеваний, precision medicine и фармакогеномика, лечение рака, research, forensic, анализ микробиома итд
- первичная обработка - от сырых данных к мутациям
- манипуляции последовательностями днк: выравнивания, постороение фило деревьев итд
- диагностика менделевских заболеваний - OMIM
- диагностика более сложных заболеваний, GWAS, Molecular Profiling
- forensic 

получается очень много - и моя задача как-то втистуть это в 20 минут )))

**Comment by shurph** [comment]
Выступление состоялось 26.05.2021.
Видео: https://www.youtube.com/watch?v=BF1rI_r-0BY&list=PLjiAaL1HtGPZryLkhGv-oxwWQwvs50t26&index=5
