### ISSUE TITLE
Kuberneтизируемся

### ISSUE THREAD

**Issue by Gr1N** [minskpython/talks#49]
Рассказ одной компании о своей миграции в k8s, зачем, почему, подводные камни и вообще стоило ли оно того.

**Comment by shurph** [comment]
Выступление состоялось 31.03.2021.
Видео: https://www.youtube.com/watch?v=7x4wgwWDnf4&list=PLjiAaL1HtGPZryLkhGv-oxwWQwvs50t26&index=2
