### ISSUE TITLE
Питон в некроBMW

### ISSUE THREAD

**Issue by shushkaden** [minskpython/talks#55]
**Название доклада**:
Питон в некроBMW

**Описание доклада**:
Это история о том, как я захотел пописать код для своей любимой машины, как я узнал про [micropython](https://micropython.org/), научился паять и что в итоге получилось.

**Укажите, пожалуйста, как связаться со спикером**:
https://www.facebook.com/denis.shushkevich.1/

**Comment by shurph** [comment]
Выступление состоялось 21.04.2021.
Видео: https://www.youtube.com/watch?v=gw7Q9L9nF7I&list=PLjiAaL1HtGPZryLkhGv-oxwWQwvs50t26&index=5
