### ISSUE TITLE
Sampling Profiling in Python: глазами обычного программиста

### ISSUE THREAD

**Issue by staaas** [minskpython/talks#8]

**Comment by shurph** [comment]
Sampling Profiling on Production Systems to Find Bottleneck in Realtime
https://www.youtube.com/watch?v=DXVsvnfr6qg

https://www.devopspro.ru/2018/wp-content/uploads/2018/11/1D-H3-2-Eugen-Klimov-min.pdf

https://devconf.ru/ru/archive/devconf2018/offer/371
